---
# tasks file for apache

- name: install apache package
  yum:
    name:  httpd
    state: latest

- name: start and enable apache at boot
  service:
    name: httpd
    enabled: yes
    state: started
